const internshipExperiences = {
  Facebook: [
    {
      name: 'Bradd Hogg',
      contact: '999999',
      profile: 'Software Engineer',
      caption: 'You Can Do It',
      date: '07/01/2019',
      imageLink: '/img/yuna.jpg',
      q_shortlisting:
        'In the written round the first we had an aptitude kind of a test. 40 students were shortlisted from this test. Then we had a coding round which consisted of 3 coding questions. The students having the highest percentages were among those 40 students were shortlisted for interviews. We had one technical interview in which pretty simple questions were asked. Then we had an HR which was also very easy.',
      q_interview:
        'I got a PPO. The only advice would complete the given tasks on time. If you feel so that you have completed the work assigned to you then don’t waste time and go and ask for more work. It is very important to maintain good relations with your manager so go and meet him atleast once a week and brief him about the work that you have done.',
      q_resources:
        'Well since i was doing an internship so i could not prepare immediately before  the placement season. The only thing which i have done is competitive programming and i doing it since the past 2-3 years. Though this is not a very long period. So my advice would be to start online programming as early as possible. Along with online programming i had referred to a few books like The C Programming language Dennis Ritche Algorithms CLRS Placement preparation Cracking the Coding Interview',
      q_additional:
        'I was rejected by approximately 12 companies before i got my first job at Samsung. The only advice would be to keep patience and stay confident.',
      id: '123',
    },
    {
      name: 'Shane Warne',
      contact: '999999',
      profile: 'Data Analyst',
      caption: 'You Can Do It',
      date: '07/01/2019',
      imageLink: '/img/yuna.jpg',
      q_shortlisting: '',
      q_interview: '',
      q_resources: '',
      q_additional: '',
      id: '155',
    },
  ],
  Google: [
    {
      name: 'Brett Lee',
      contact: '999999',
      profile: 'Software Engineer',
      caption: 'You Can Do It',
      date: '07/01/2019',
      imageLink: '/img/yuna.jpg',
      q_shortlisting: '',
      q_interview: '',
      q_resources: '',
      q_additional: '',
      id: '923',
    },
    {
      name: 'Michael Clarke',
      contact: '999999',
      profile: 'Data Analyst',
      caption: 'You Can Do It',
      date: '07/01/2019',
      imageLink: '/img/yuna.jpg',
      q_shortlisting: '',
      q_interview: '',
      q_resources: '',
      q_additional: '',
      id: '823',
    },
    {
      name: 'Bradd Hogg',
      contact: '999999',
      profile: 'Software Engineer',
      caption: 'You Can Do It',
      date: '07/01/2019',
      imageLink: '/img/yuna.jpg',
      q_shortlisting: '',
      q_interview: '',
      q_resources: '',
      q_additional: '',
      id: '723',
    },
  ],
  Amazon: [
    {
      name: 'Bradd Hogg',
      contact: '999999',
      profile: 'Data Analyst',
      caption: 'You Can Do It',
      date: '07/01/2019',
      imageLink: '/img/yuna.jpg',
      q_shortlisting: '',
      q_interview: '',
      q_resources: '',
      q_additional: '',
      id: '623',
    },
    {
      name: 'Michael Clarke',
      contact: '999999',
      profile: 'Software Engineer',
      caption: 'You Can Do It',
      date: '07/01/2019',
      imageLink: '/img/yuna.jpg',
      q_shortlisting: '',
      q_interview: '',
      q_resources: '',
      q_additional: '',
      id: '523',
    },
  ],
  Nvidia: [],
  Microsoft: [
    {
      name: 'Brett Lee',
      contact: '999999',
      profile: 'Data Analyst',
      caption: 'You Can Do It',
      date: '07/01/2019',
      imageLink: '/img/yuna.jpg',
      q_shortlisting: '',
      q_interview: '',
      q_resources: '',
      q_additional: '',
      id: '423',
    },
  ],
  Texas: [],
};

export default internshipExperiences;
