export const SET_HEADING = 'SET_HEADING';
export const SET_TEAMDATA = 'SET_TEAMDATA';
export const SET_LOADING = 'SET_LOADING';
export const SET_EXAMPAPERS = 'SET_EXAMPAPERS';
export const SET_LEARNSPACEDATA = 'SET_LEARNSPACEDATA';
